//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_TTCD1_DinhTienLuc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetail
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Hãy chọn khách hàng")]
        public int OrderId { get; set; }
        [Required(ErrorMessage = "Hãy chọn Sách hàng")]
        public int SachId { get; set; }
        [Required(ErrorMessage = "Hãy nhập giá")]
        public decimal Price { get; set; }
        [Required(ErrorMessage = "Hãy nhập số lượng")]
        public int Quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
