//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_TTCD1_DinhTienLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public int IdSach { get; set; }
        public int IdUser { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quatity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual SachTb SachTb { get; set; }
        public virtual User User { get; set; }
    }
}
